import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

const root = new URL("../", import.meta.url);
const sections = JSON.parse(
  await readFile(new URL("src/sections.json", root), "utf8"),
);
const contents = await Promise.all(
  sections.map((name) => readFile(new URL(`src/${name}`, root), "utf8")),
);
const body = contents
  .map((source, index) => {
    const label = `// ---- src/${sections[index]} ----\n`;
    return (label + source.trimEnd())
      .split("\n")
      .map((line) => (line ? `  ${line}` : ""))
      .join("\n");
  })
  .join("\n\n");
const output = `// Generated by npm run build. Edit src/ files instead.\n(() => {\n  "use strict";\n\n${body}\n})();\n`;
const target = new URL("game.js", root);

if (process.argv.includes("--check")) {
  const current = await readFile(target, "utf8").catch(() => "");
  if (current !== output) {
    console.error(
      "game.js is out of date. Run npm run build and commit the result.",
    );
    process.exitCode = 1;
  } else {
    console.log("game.js matches the source sections.");
  }
} else {
  await writeFile(target, output);
  console.log(
    `Built ${fileURLToPath(target)} from ${sections.length} source sections.`,
  );
}
